import { jest } from "@jest/globals";
import mongoose from "mongoose";

describe("autoContractOrchestratorService", () => {
  let autoGenerateDepositSettledContract;
  let autoGenerateMoveInContract;
  let autoGenerateTransferContract;
  let mockContractFindOne;
  let mockContractUpdateOne;
  let mockContractFindById;
  let mockReservationFindById;
  let mockUserFindById;
  let autoGenerateRenewalContract;
  let mockCreateDraftContract;
  let mockCreateReplacementContractForTransfer;
  let mockCreateSuccessorContractForRenewal;
  let mockValidateContractForGeneration;
  let mockTransitionContract;
  let mockGeneratePreparedContractPdf;
  let mockNotifyBranchAdmins;

  beforeEach(async () => {
    jest.resetModules();

    mockContractFindOne = jest.fn();
    mockContractUpdateOne = jest.fn().mockResolvedValue({});
    mockContractFindById = jest.fn();
    mockReservationFindById = jest.fn();
    mockUserFindById = jest.fn();
    mockCreateDraftContract = jest.fn();
    mockCreateReplacementContractForTransfer = jest.fn();
    mockCreateSuccessorContractForRenewal = jest.fn();
    mockValidateContractForGeneration = jest.fn().mockResolvedValue({
      valid: true,
      status: "ready_for_generation",
      template: { templateId: "tpl1", templateVersion: 1, legalContentVersion: 1 },
      generationData: { pricing: { approvedMonthlyRate: 6000 } },
    });
    mockTransitionContract = jest.fn().mockImplementation(async (c, s) => {
      c.status = s;
      return c;
    });
    mockGeneratePreparedContractPdf = jest.fn();

    jest.unstable_mockModule("./renewalContractPreparationService.js", () => ({
      withRenewalPreparationLock: (_stayId, prepare) => prepare(),
    skipBlockedRenewalPreparation: jest.fn().mockResolvedValue(null),
      clearRenewalPreparationFailure: jest.fn().mockResolvedValue(null),
      recordRenewalPreparationFailure: jest.fn(async (_, e) => ({ success: false, error: e.code || e.message, code: e.code })),
    }));
    jest.unstable_mockModule("../models/index.js", () => ({
      Contract: {
        findOne: mockContractFindOne,
        updateOne: mockContractUpdateOne,
        findById: mockContractFindById,
      },
      Reservation: {
        findById: mockReservationFindById,
      },
      User: {
        findById: mockUserFindById,
      },
      Room: {
        findById: jest.fn(),
      },
      Stay: {
        find: jest.fn(),
      },
    }));

    jest.unstable_mockModule("./contractService.js", () => ({
      createDraftContract: mockCreateDraftContract,
      createReplacementContractForTransfer: mockCreateReplacementContractForTransfer,
      createSuccessorContractForRenewal: mockCreateSuccessorContractForRenewal,
      validateContractForGeneration: mockValidateContractForGeneration,
      getContractValidation: jest.fn(() => ({ valid: true, missingFields: [] })),
      transitionContract: mockTransitionContract,
    }));

    jest.unstable_mockModule("./contractPdfService.js", () => ({
      generatePreparedContractPdf: mockGeneratePreparedContractPdf,
    }));

    jest.unstable_mockModule("../utils/notificationService.js", () => ({
      notify: {
        contractDocumentReady: jest.fn().mockResolvedValue(true),
      },
      notifyBranchAdmins: jest.fn().mockResolvedValue([]),
    }));

    jest.unstable_mockModule("../utils/socket.js", () => ({
      emitToUser: jest.fn(),
      emitToAdmins: jest.fn(),
    }));

    // notifyBranchAdminsSafe() dynamically imports this exact relative path
    // (server/services/notifications/notificationService.js) — distinct from
    // the "../utils/notificationService.js" mock above, which only backs the
    // unrelated static `notify` import at the top of the module under test.
    mockNotifyBranchAdmins = jest.fn().mockResolvedValue([]);
    jest.unstable_mockModule("./notifications/notificationService.js", () => ({
      notifyBranchAdmins: mockNotifyBranchAdmins,
    }));

    const mod = await import("./autoContractOrchestratorService.js");
    autoGenerateDepositSettledContract = mod.autoGenerateDepositSettledContract;
    autoGenerateMoveInContract = mod.autoGenerateMoveInContract;
    autoGenerateTransferContract = mod.autoGenerateTransferContract;
    autoGenerateRenewalContract = mod.autoGenerateRenewalContract;
  });

  describe("autoGenerateMoveInContract", () => {
    test("creates a draft contract, validates it, and generates PDF when no contract exists", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId, roomId: "room123", currentStayId: "stay123" }),
      });
      mockContractFindOne.mockResolvedValueOnce(null);

      const createdDraft = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00001",
        status: "draft",
        branch: "manila",
        roomNumber: "101",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };
      mockCreateDraftContract.mockResolvedValue(createdDraft);
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...createdDraft, status: "generated" },
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Juan", lastName: "Dela Cruz" }),
        }),
      });

      const result = await autoGenerateMoveInContract({ reservationId: resId, actorId });

      expect(result.success).toBe(true);
      expect(mockCreateDraftContract).toHaveBeenCalledWith(
        expect.objectContaining({ reservationId: resId, actorId }),
      );
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId }),
      );
    });

    test("generates PDF for an existing ready_for_generation draft without recreating it", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId }),
      });
      const existingDraft = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00002",
        status: "ready_for_generation",
        branch: "manila",
        roomNumber: "102",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };
      mockContractFindOne.mockResolvedValueOnce(existingDraft);
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...existingDraft, status: "generated" },
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Maria", lastName: "Santos" }),
        }),
      });

      const result = await autoGenerateMoveInContract({ reservationId: resId, actorId });

      expect(result.success).toBe(true);
      expect(mockCreateDraftContract).not.toHaveBeenCalled();
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId }),
      );
    });

    // Regression: contractPdfService.js's allowedStatuses accepts "generated"
    // directly for regeneration, but the outer gate in this function only
    // re-enters the generate path for draft/incomplete/ready_for_generation
    // — so a "generated" Contract still has to be demoted to
    // "ready_for_generation" to be regenerated at all. What changed: if
    // regeneration then fails for any reason, the Contract must be reverted
    // back to "generated" (not left stuck at "ready_for_generation", which
    // hides its still-untouched, still-valid prior Draft from
    // tenantDocument resolution) instead of silently losing tenant access.
    test("a successful realignment + regeneration on a 'generated' contract completes without error", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId }),
      });
      const generatedContract = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00007",
        status: "generated",
        branch: "manila",
        roomNumber: "107",
        tenantId: "tenant123",
        leaseDurationMonths: 6,
        leaseStartDate: new Date("2026-01-01"),
        leaseEndDate: new Date("2026-07-01"),
        finalDocument: null,
        save: jest.fn().mockResolvedValue(true),
      };
      mockContractFindOne.mockResolvedValueOnce(generatedContract);
      // Reflects the DB state the code re-reads after its own updateOne
      // demotes status to re-enter the generation gate.
      mockContractFindById.mockResolvedValueOnce({ ...generatedContract, status: "ready_for_generation" });
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...generatedContract, status: "generated" },
        document: { version: 2 },
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Maria", lastName: "Santos" }),
        }),
      });

      const result = await autoGenerateMoveInContract({
        reservationId: resId,
        actorId,
        actualMoveInDate: new Date("2026-02-01"),
      });

      expect(result.success).toBe(true);
      expect(mockContractUpdateOne).toHaveBeenCalledWith(
        { _id: contractId },
        { $set: expect.objectContaining({ status: "ready_for_generation" }) },
      );
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId, regenerationReason: expect.any(String) }),
      );
    });

    test("a failed regeneration on a 'generated' contract reverts status instead of leaving the prior Draft hidden", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId }),
      });
      const generatedContract = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00008",
        status: "generated",
        branch: "manila",
        roomNumber: "108",
        tenantId: "tenant123",
        leaseDurationMonths: 6,
        leaseStartDate: new Date("2026-01-01"),
        leaseEndDate: new Date("2026-07-01"),
        finalDocument: null,
        save: jest.fn().mockResolvedValue(true),
      };
      mockContractFindOne.mockResolvedValueOnce(generatedContract);
      mockContractFindById.mockResolvedValueOnce({ ...generatedContract, status: "ready_for_generation" });
      mockGeneratePreparedContractPdf.mockRejectedValueOnce(
        Object.assign(new Error("RESERVATION_FEE_PAYMENT_NOT_VERIFIED"), { code: "CONTRACT_GENERATION_VALIDATION_FAILED" }),
      );

      const result = await autoGenerateMoveInContract({
        reservationId: resId,
        actorId,
        actualMoveInDate: new Date("2026-02-01"),
      });

      expect(result.success).toBe(false);
      // The revert is a distinct, guarded call: only flips status back to
      // "generated", and only if it's still "ready_for_generation" (no
      // concurrent change since this invocation's own demotion).
      expect(mockContractUpdateOne).toHaveBeenCalledWith(
        { _id: contractId, status: "ready_for_generation" },
        { $set: { status: "generated" } },
      );
    });

    test("notifies branch admins with contract_incomplete when auto-validation fails", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId }),
      });
      const draft = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00003",
        status: "draft",
        branch: "manila",
        roomNumber: "103",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };
      mockContractFindOne.mockResolvedValueOnce(draft);
      mockValidateContractForGeneration.mockResolvedValueOnce({
        valid: false,
        status: "incomplete",
        missingFields: [{ field: "tenantBirthDate", label: "Tenant birth date" }],
        errors: [],
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Juan", lastName: "Dela Cruz" }),
        }),
      });

      const result = await autoGenerateMoveInContract({ reservationId: resId, actorId });

      expect(result.success).toBe(true);
      expect(result.incomplete).toBe(true);
      expect(mockGeneratePreparedContractPdf).not.toHaveBeenCalled();
      expect(mockNotifyBranchAdmins).toHaveBeenCalledWith(
        "manila",
        "contract_incomplete",
        expect.any(String),
        expect.stringContaining("Tenant birth date"),
        expect.objectContaining({ entityType: "contract", entityId: String(contractId) }),
      );
    });

    test("handles PDF generation errors gracefully without throwing", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId }),
      });
      mockContractFindOne.mockResolvedValueOnce({
        _id: contractId,
        status: "ready_for_generation",
        save: jest.fn().mockResolvedValue(true),
      });
      mockGeneratePreparedContractPdf.mockRejectedValue(new Error("Font render failure"));

      const result = await autoGenerateMoveInContract({ reservationId: resId, actorId: "admin123" });

      expect(result.success).toBe(false);
      expect(result.error).toBe("Font render failure");
    });
  });

  describe("autoGenerateTransferContract", () => {
    test("supersedes old contract, creates replacement, validates, and generates PDF", async () => {
      const resId = new mongoose.Types.ObjectId();
      const oldContractId = new mongoose.Types.ObjectId();
      const replacementId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      const oldContract = {
        _id: oldContractId,
        contractNumber: "LIL-MNL-2026-00001",
        version: 1,
        status: "active",
        stayId: "stay123",
        roomNumber: "101",
      };

      mockContractFindOne.mockReturnValue({
        sort: jest.fn().mockReturnValue({
          _id: oldContractId,
          ...oldContract,
        }),
      });

      const replacementDoc = {
        _id: replacementId,
        contractNumber: "LIL-MNL-2026-00005",
        version: 2,
        status: "draft",
        branch: "manila",
        roomNumber: "205",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };

      mockCreateReplacementContractForTransfer.mockResolvedValue(replacementDoc);
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...replacementDoc, status: "generated" },
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Juan", lastName: "Dela Cruz" }),
        }),
      });

      const result = await autoGenerateTransferContract({
        reservationId: resId,
        activeStay: { _id: "stay123" },
        targetRoom: { _id: "room205", roomNumber: "205", branch: "manila", monthlyPrice: 8000 },
        targetBed: { id: "bedB", label: "Bed B" },
        effectiveTransferDate: new Date(),
        actorId,
      });

      expect(result.success).toBe(true);
      expect(result.replacementContractId).toBe(String(replacementId));
      expect(mockCreateReplacementContractForTransfer).toHaveBeenCalled();
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId: replacementId }),
      );
    });
  });

  describe("autoGenerateDepositSettledContract", () => {
    test("creates a draft contract, validates it, and generates prepared PDF upon deposit settlement", async () => {
      const resId = new mongoose.Types.ObjectId();
      const contractId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      mockReservationFindById.mockReturnValue({
        lean: jest.fn().mockResolvedValue({ _id: resId, roomId: "room123", userId: "tenant123" }),
      });
      mockContractFindOne.mockResolvedValueOnce(null);

      const createdDraft = {
        _id: contractId,
        contractNumber: "LIL-MNL-2026-00001",
        status: "draft",
        branch: "manila",
        roomNumber: "101",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };

      mockCreateDraftContract.mockResolvedValue(createdDraft);
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...createdDraft, status: "generated", preparedDocument: { version: 1 } },
      });

      const result = await autoGenerateDepositSettledContract({
        reservationId: resId,
        actorId,
      });

      expect(result.success).toBe(true);
      expect(result.contractId).toBe(String(contractId));
      expect(mockCreateDraftContract).toHaveBeenCalledWith(
        expect.objectContaining({ reservationId: resId }),
      );
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId }),
      );
    });
  });

  describe("autoGenerateRenewalContract", () => {
    test("creates a renewal successor, validates, and generates PDF without touching the old contract", async () => {
      const resId = new mongoose.Types.ObjectId();
      const oldContractId = new mongoose.Types.ObjectId();
      const successorId = new mongoose.Types.ObjectId();
      const actorId = new mongoose.Types.ObjectId();

      const oldContract = {
        _id: oldContractId,
        contractNumber: "LIL-MNL-2026-00001",
        version: 1,
        status: "active",
        branch: "manila",
        roomNumber: "101",
      };

      const successorDoc = {
        _id: successorId,
        contractNumber: "LIL-MNL-2026-00006",
        version: 2,
        status: "draft",
        branch: "manila",
        roomNumber: "101",
        tenantId: "tenant123",
        save: jest.fn().mockResolvedValue(true),
      };

      mockCreateSuccessorContractForRenewal.mockResolvedValue(successorDoc);
      mockGeneratePreparedContractPdf.mockResolvedValue({
        contract: { ...successorDoc, status: "generated" },
      });
      mockUserFindById.mockReturnValue({
        select: jest.fn().mockReturnValue({
          lean: jest.fn().mockResolvedValue({ firstName: "Juan", lastName: "Dela Cruz" }),
        }),
      });

      const result = await autoGenerateRenewalContract({
        reservationId: resId,
        oldContract,
        newStay: { _id: "stay456", leaseStartDate: new Date(), leaseEndDate: new Date(), monthlyRent: 6800 },
        actorId,
      });

      expect(result.success).toBe(true);
      expect(result.successorContractId).toBe(String(successorId));
      expect(mockCreateSuccessorContractForRenewal).toHaveBeenCalledWith(
        expect.objectContaining({ reservationId: resId, oldContract }),
      );
      expect(mockGeneratePreparedContractPdf).toHaveBeenCalledWith(
        expect.objectContaining({ contractId: successorId }),
      );
      // The old contract is passed through untouched — no status/isCurrent
      // mutation happens in this orchestrator (that only ever happens in
      // contractRenewalActivationService at the successor's effective date).
      expect(oldContract.status).toBe("active");
      expect(oldContract.isCurrent).toBeUndefined();
    });

    test("returns a non-throwing failure when no current contract is provided", async () => {
      const resId = new mongoose.Types.ObjectId();
      const result = await autoGenerateRenewalContract({
        reservationId: resId,
        oldContract: null,
        newStay: { _id: "stay456" },
        actorId: new mongoose.Types.ObjectId(),
      });
      expect(result.success).toBe(false);
      expect(result.error).toBe("PREVIOUS_CONTRACT_REQUIRED");
      expect(mockCreateSuccessorContractForRenewal).not.toHaveBeenCalled();
    });
  });
});
