import dayjs from "dayjs";
import logger from "../middleware/logger.js";
import { Contract, Reservation, Room, User } from "../models/index.js";
import { notify } from "../utils/notificationService.js";
import { emitToUser, emitToAdmins } from "../utils/socket.js";
import {
  createDraftContract,
  createReplacementContractForTransfer,
  createSuccessorContractForRenewal,
  transitionContract,
  validateContractForGeneration,
} from "./contractService.js";
import { generatePreparedContractPdf } from "./contractPdfService.js";
import { repairContractDraftDates } from "./contractDraftRecoveryService.js";
import {
  deriveAdvanceCoverageDates,
  deriveContractLeaseDates,
} from "./contractLeaseDateService.js";
import { readMoveInDate } from "../utils/lifecycleNaming.js";

const recoverExistingDraftDates = async ({ contract, actorId }) => {
  if (
    contract?.status !== "draft" ||
    contract.leaseStartDate !== null ||
    contract.leaseEndDate !== null
  ) {
    return contract;
  }
  const recovery = await repairContractDraftDates({ contractId: contract._id, actorId });
  return recovery.contract || contract;
};

const selfHealContractIdentityFromReservation = async ({ contract, reservation, actorId }) => {
  if (!contract || !reservation) return contract;

  let hasUpdates = false;
  const updates = {};

  const tenantNationality = reservation.nationality || reservation.userId?.nationality;
  if (!contract.tenantNationality && tenantNationality) {
    updates.tenantNationality = tenantNationality;
    contract.tenantNationality = tenantNationality;
    hasUpdates = true;
  }

  const tenantBirthday = reservation.birthday || reservation.userId?.birthday;
  if (!contract.tenantBirthDate && tenantBirthday) {
    const birthDate = new Date(tenantBirthday);
    if (!isNaN(birthDate.getTime())) {
      updates.tenantBirthDate = birthDate;
      contract.tenantBirthDate = birthDate;
      hasUpdates = true;
    }
  }

  const tenantPhone = reservation.phone || reservation.mobileNumber || reservation.userId?.phone;
  if (!contract.tenantPhone && tenantPhone) {
    updates.tenantPhone = tenantPhone;
    contract.tenantPhone = tenantPhone;
    hasUpdates = true;
  }

  if (!contract.tenantAddress) {
    const rawAddress = reservation.address || reservation.userId?.address;
    const formatted = typeof rawAddress === "object"
      ? [rawAddress.unitHouseNo, rawAddress.street, rawAddress.barangay, rawAddress.city, rawAddress.province].filter(Boolean).join(", ")
      : String(rawAddress || "").trim();
    if (formatted) {
      updates.tenantAddress = formatted;
      contract.tenantAddress = formatted;
      hasUpdates = true;
    }
  }

  if (!contract.tenantLegalName) {
    const name = [reservation.firstName, reservation.middleName, reservation.lastName].filter(Boolean).join(" ").trim()
      || [reservation.userId?.firstName, reservation.userId?.lastName].filter(Boolean).join(" ").trim();
    if (name) {
      updates.tenantLegalName = name;
      contract.tenantLegalName = name;
      hasUpdates = true;
    }
  }

  const moveInDate = readMoveInDate(reservation);
  if (!contract.leaseStartDate && moveInDate) {
    const moveInDateObj = new Date(moveInDate);
    if (!isNaN(moveInDateObj.getTime())) {
      const duration = Number(contract.leaseDurationMonths || reservation.leaseDuration || 12);
      const leaseDates = deriveContractLeaseDates({
        leaseStartDate: moveInDateObj,
        leaseDurationMonths: duration,
      });
      const coverageDates = deriveAdvanceCoverageDates(moveInDateObj);
      updates.leaseStartDate = leaseDates.leaseStartDate;
      updates.leaseEndDate = leaseDates.leaseEndDate;
      updates.leaseDurationMonths = duration;
      updates.advanceCoverageStart = coverageDates.advanceCoverageStart;
      updates.advanceCoverageEnd = coverageDates.advanceCoverageEnd;
      Object.assign(contract, updates);
      hasUpdates = true;
    }
  }

  if (hasUpdates) {
    if (actorId) updates.updatedBy = actorId;
    if (typeof contract.save === "function") {
      await contract.save();
    } else if (typeof Contract.updateOne === "function") {
      await Contract.updateOne({ _id: contract._id }, { $set: updates });
    }
  }

  return contract;
};

/**
 * Automatically creates and generates a prepared PDF contract when an applicant's
 * initial advance rent and security deposit payments are confirmed.
 *
 * Provides early assurance and access to the official Generated Draft before Move-In.
 *
 * @param {Object} params
 * @param {string|mongoose.Types.ObjectId} params.reservationId
 * @param {string|mongoose.Types.ObjectId} [params.actorId]
 * @returns {Promise<{ success: boolean, contractId?: string, error?: string }>}
 */
export async function autoGenerateDepositSettledContract({ reservationId, actorId }) {
  try {
    let resQuery = Reservation.findById(reservationId);
    if (resQuery && typeof resQuery.populate === "function") {
      resQuery = resQuery.populate("userId", "firstName lastName email phone nationality birthday address");
    }
    const reservation = resQuery && typeof resQuery.lean === "function" ? await resQuery.lean() : await resQuery;
    if (!reservation) {
      logger.warn({ reservationId }, "[AutoContract] Deposit-settled contract skipped: Reservation not found");
      return { success: false, error: "RESERVATION_NOT_FOUND" };
    }

    let contract = await Contract.findOne({
      reservationId: reservation._id,
      isCurrent: true,
    });

    if (!contract) {
      logger.info({ reservationId: reservation._id }, "[AutoContract] Creating initial draft upon Advance & Deposit settlement");
      contract = await createDraftContract({
        reservationId: reservation._id,
        stayId: reservation.currentStayId || null,
        actorId,
        allowedBranch: null,
      });
    } else {
      contract = await recoverExistingDraftDates({ contract, actorId });
    }

    contract = await selfHealContractIdentityFromReservation({ contract, reservation, actorId });

    if (["draft", "incomplete", "ready_for_generation"].includes(contract.status)) {
      if (contract.status !== "ready_for_generation") {
        const validation = await validateContractForGeneration(contract);
        if (validation.valid) {
          await transitionContract(contract, "ready_for_generation", actorId, "Contract auto-validated upon Advance & Deposit settlement");
          Object.assign(contract, validation.generationData.pricing);
          contract.templateType = validation.template.templateId;
          contract.templateVersion = validation.template.templateVersion;
          contract.legalContentVersion = validation.template.legalContentVersion;
          contract.validatedGenerationData = validation.generationData;
          contract.lastValidatedAt = new Date();
          contract.updatedBy = actorId;
          await contract.save();
        } else {
          const moveIn = readMoveInDate(reservation, { includeSource: true });
          logger.warn(
            {
              contractId: contract._id,
              contractNumber: contract.contractNumber,
              reservationId: reservation._id,
              tenantId: contract.tenantId,
              missingRequiredField: validation.missingFields?.[0]?.field || null,
              resolvedMoveInDateSource: moveIn.sourceField,
              currentLifecycleStatus: contract.status,
              blockingReason: validation.errors?.[0]?.code || validation.missingFields?.[0]?.field || null,
              missing: validation.missingFields,
              errors: validation.errors,
            },
            "[AutoContract] Deposit-settled contract incomplete; draft saved for review",
          );
          return {
            success: true,
            contractId: String(contract._id),
            contractNumber: contract.contractNumber,
            status: contract.status,
            incomplete: true,
          };
        }
      }

      logger.info({ contractId: contract._id, contractNumber: contract.contractNumber }, "[AutoContract] Generating prepared PDF upon Advance & Deposit settlement");
      const result = await generatePreparedContractPdf({
        contractId: contract._id,
        actorId,
        regenerationReason: "Auto-generated upon Advance Rent & Deposit settlement",
      });

      const tenantUserId = reservation?.userId || contract?.tenantId;
      if (tenantUserId) {
        if (typeof notify?.contractDocumentReady === "function") {
          notify
            .contractDocumentReady(
              tenantUserId,
              "prepared",
              result.contract._id,
              result.document?.version || 1,
            )
            .catch((e) => logger.warn({ err: e }, "[AutoContract] Tenant notification failed (non-fatal)"));
        }

        if (typeof emitToUser === "function") {
          emitToUser(tenantUserId, "contract:updated", {
            contractId: String(result.contract._id),
            contractNumber: result.contract.contractNumber,
            status: result.contract.status,
            reservationId: String(reservation._id),
          });
        }
      }

      if (typeof emitToAdmins === "function") {
        emitToAdmins("contract:updated", {
          contractId: String(result.contract._id),
          contractNumber: result.contract.contractNumber,
          status: result.contract.status,
          branch: result.contract.branch,
        });
      }

      return { success: true, contractId: String(result.contract._id), contractNumber: result.contract.contractNumber };
    }

    return { success: true, contractId: String(contract._id), status: contract.status };
  } catch (error) {
    logger.error({ err: error, reservationId }, "[AutoContract] Failed to auto-generate Deposit-Settled contract");
    return { success: false, error: error.message, code: error.code };
  }
}

/**
 * Automatically creates/updates and generates a prepared PDF contract when a tenant
 * moves in (status: 'moveIn'). Automatically realigns lease start & end dates to the actual
 * move-in date.
 *
 * Runs asynchronously to prevent blocking the check-in HTTP response.
 *
 * @param {Object} params
 * @param {string|mongoose.Types.ObjectId} params.reservationId
 * @param {Date|string} [params.actualMoveInDate]
 * @param {string|mongoose.Types.ObjectId} params.actorId
 * @returns {Promise<{ success: boolean, contractId?: string, error?: string }>}
 */
export async function autoGenerateMoveInContract({ reservationId, actualMoveInDate, actorId }) {
  // Tracks whether this invocation demoted an already-"generated" Contract
  // to "ready_for_generation" to re-enter the generation gate below — if
  // regeneration then fails for any reason, the catch block reverts this
  // so the still-valid prior Draft (its preparedDocuments entry is
  // untouched either way — contractPdfService.js only supersedes it after
  // a new one is successfully stored) becomes visible again immediately,
  // instead of being hidden until someone notices and manually retries.
  let demotedGeneratedContractId = null;
  try {
    const reservation = await Reservation.findById(reservationId).lean();
    if (!reservation) {
      logger.warn({ reservationId }, "[AutoContract] Move-in contract skipped: Reservation not found");
      return { success: false, error: "RESERVATION_NOT_FOUND" };
    }

    let contract = await Contract.findOne({
      reservationId: reservation._id,
      isCurrent: true,
    });

    if (!contract) {
      logger.info({ reservationId: reservation._id }, "[AutoContract] Creating initial draft for Move-In");
      contract = await createDraftContract({
        reservationId: reservation._id,
        stayId: reservation.currentStayId || null,
        actorId,
        allowedBranch: null,
      });
    }

    contract = await recoverExistingDraftDates({ contract, actorId });

    // Realign / adjust lease dates if actualMoveInDate is provided and contract is not finalized
    const moveInResolution = actualMoveInDate
      ? { value: actualMoveInDate, sourceField: "actualMoveInDate" }
      : readMoveInDate(reservation, { includeSource: true });
    if (moveInResolution.value && !contract.finalDocument?.storageKey) {
      const moveInDateObj = new Date(moveInResolution.value);
      if (!isNaN(moveInDateObj.getTime())) {
        const durationMonths = contract.leaseDurationMonths ||
          (contract.leaseStartDate && contract.leaseEndDate
            ? Math.max(1, dayjs(contract.leaseEndDate).diff(dayjs(contract.leaseStartDate), "month"))
            : 12);

        const leaseDates = deriveContractLeaseDates({
          leaseStartDate: moveInDateObj,
          leaseDurationMonths: durationMonths,
        });
        const coverageDates = deriveAdvanceCoverageDates(moveInDateObj);

        const updateFields = {
          leaseStartDate: leaseDates.leaseStartDate,
          leaseEndDate: leaseDates.leaseEndDate,
          leaseDurationMonths: durationMonths,
          advanceCoverageStart: coverageDates.advanceCoverageStart,
          advanceCoverageEnd: coverageDates.advanceCoverageEnd,
        };

        // Demotion is required to re-enter the generation gate below (it
        // only accepts draft/incomplete/ready_for_generation) — but if the
        // Contract was already "generated", remember that so a failed
        // regeneration can be safely reverted instead of leaving the
        // Contract stuck invisible with its still-valid prior Draft intact
        // but unreachable.
        if (contract.status === "generated" || contract.status === "awaiting_signatures") {
          if (contract.status === "generated") demotedGeneratedContractId = contract._id;
          updateFields.status = "ready_for_generation";
        }

        await Contract.updateOne({ _id: contract._id }, { $set: updateFields });
        contract = await Contract.findById(contract._id);
      }
    }

    if (["draft", "incomplete", "ready_for_generation"].includes(contract.status)) {
      if (contract.status !== "ready_for_generation") {
        const validation = await validateContractForGeneration(contract);
        if (validation.valid) {
          await transitionContract(contract, "ready_for_generation", actorId, "Contract auto-validated for PDF generation");
          Object.assign(contract, validation.generationData.pricing);
          contract.templateType = validation.template.templateId;
          contract.templateVersion = validation.template.templateVersion;
          contract.legalContentVersion = validation.template.legalContentVersion;
          contract.validatedGenerationData = validation.generationData;
          contract.lastValidatedAt = new Date();
          contract.updatedBy = actorId;
          await contract.save();
        } else {
          logger.warn(
            {
              contractId: contract._id,
              contractNumber: contract.contractNumber,
              reservationId: reservation._id,
              tenantId: contract.tenantId,
              missingRequiredField: validation.missingFields?.[0]?.field || null,
              resolvedMoveInDateSource: moveInResolution.sourceField,
              currentLifecycleStatus: contract.status,
              blockingReason: validation.errors?.[0]?.code || validation.missingFields?.[0]?.field || null,
              missing: validation.missingFields,
              errors: validation.errors,
            },
            "[AutoContract] Contract validation incomplete; draft created for administrator review",
          );

          try {
            const tenant = await User.findById(contract.tenantId).select("firstName lastName email").lean();
            const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}`.trim() : contract.tenantLegalName || "Tenant";
            const missingSummary = validation.missingFields.map((f) => f.label).join(", ")
              || validation.errors.map((e) => e.message).join(", ")
              || "additional information";
            await notifyBranchAdminsSafe(
              contract.branch,
              "contract_incomplete",
              "Contract Needs Information Before It Can Be Generated",
              `Move-in contract for ${tenantName} (Room ${contract.roomNumber}) could not be auto-generated: missing ${missingSummary}. Complete it in the Contracts workspace.`,
              {
                entityType: "contract",
                entityId: String(contract._id),
                reservationId: contract.reservationId ? String(contract.reservationId) : null,
                actionUrl: contract.reservationId
                  ? `/admin/tenants?reservationId=${encodeURIComponent(String(contract.reservationId))}`
                  : "/admin/tenants",
              },
            );
          } catch (notifErr) {
            logger.warn({ err: notifErr }, "[AutoContract] Incomplete-contract notification error (non-fatal)");
          }

          return {
            success: true,
            contractId: String(contract._id),
            contractNumber: contract.contractNumber,
            status: contract.status,
            incomplete: true,
          };
        }
      }

      logger.info({ contractId: contract._id, contractNumber: contract.contractNumber }, "[AutoContract] Generating prepared PDF on Move-In");
      const result = await generatePreparedContractPdf({
        contractId: contract._id,
        actorId,
        regenerationReason: "Auto-generated upon Move-In confirmation",
      });

      try {
        const tenant = await User.findById(contract.tenantId).select("firstName lastName email").lean();
        const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}`.trim() : contract.tenantLegalName || "Tenant";
        notifyBranchAdminsSafe(
          contract.branch,
          "contract_prepared",
          "Prepared Contract Ready for Signing",
          `Move-in contract for ${tenantName} (Room ${contract.roomNumber}) was auto-generated and is ready to print.`,
          {
            entityType: "contract",
            entityId: String(contract._id),
            reservationId: contract.reservationId ? String(contract.reservationId) : null,
            actionUrl: contract.reservationId
              ? `/admin/tenants?reservationId=${encodeURIComponent(String(contract.reservationId))}`
              : "/admin/tenants",
          },
        );
      } catch (notifErr) {
        logger.warn({ err: notifErr }, "[AutoContract] Post-generation notification error (non-fatal)");
      }

      const moveInTenantId = reservation?.userId || contract?.tenantId;
      if (moveInTenantId) {
        if (typeof notify?.contractDocumentReady === "function") {
          notify
            .contractDocumentReady(
              moveInTenantId,
              "prepared",
              result.contract._id,
              result.document?.version || 1,
            )
            .catch((e) => logger.warn({ err: e }, "[AutoContract] Tenant notification failed (non-fatal)"));
        }

        if (typeof emitToUser === "function") {
          emitToUser(moveInTenantId, "contract:updated", {
            contractId: String(result.contract._id),
            contractNumber: result.contract.contractNumber,
            status: result.contract.status,
            reservationId: String(reservationId),
          });
        }
      }

      if (typeof emitToAdmins === "function") {
        emitToAdmins("contract:updated", {
          contractId: String(result.contract._id),
          contractNumber: result.contract.contractNumber,
          status: result.contract.status,
          branch: result.contract.branch,
        });
      }

      return { success: true, contractId: String(result.contract._id), contractNumber: result.contract.contractNumber };
    }

    logger.info({ contractId: contract._id, status: contract.status }, "[AutoContract] Contract already progressed beyond draft stage");
    return { success: true, contractId: String(contract._id), status: contract.status };
  } catch (error) {
    logger.error({ err: error, reservationId }, "[AutoContract] Failed to auto-generate Move-In contract");
    if (demotedGeneratedContractId) {
      try {
        await Contract.updateOne({ _id: demotedGeneratedContractId, status: "ready_for_generation" }, { $set: { status: "generated" } });
        logger.warn(
          { contractId: demotedGeneratedContractId },
          "[AutoContract] Regeneration failed — reverted Contract status to 'generated' so the prior valid Draft remains visible",
        );
      } catch (revertErr) {
        logger.error({ err: revertErr, contractId: demotedGeneratedContractId }, "[AutoContract] Failed to revert Contract status after failed regeneration");
      }
    }
    try {
      const reservation = await Reservation.findById(reservationId).select("roomId").populate("roomId", "branch").lean();
      const branch = reservation?.roomId?.branch || "";
      notifyBranchAdminsSafe(
        branch,
        "contract_error",
        "Contract Auto-Generation Alert",
        `Move-in contract auto-generation encountered an issue: ${error.message || "Unknown error"}. Review required in Contracts workspace.`,
        {
          entityType: "reservation",
          entityId: String(reservationId),
          reservationId: String(reservationId),
          actionUrl: `/admin/tenants?reservationId=${encodeURIComponent(String(reservationId))}`,
        },
      );
    } catch (alertErr) {
      // Non-fatal
    }
    return { success: false, error: error.message, code: error.code };
  }
}

/**
 * Automatically supersedes the old contract and generates a full replacement
 * contract when a tenant transfers rooms (transferStayWorkflow).
 *
 * @param {Object} params
 * @param {string|mongoose.Types.ObjectId} params.reservationId
 * @param {Object} params.activeStay
 * @param {Object} params.targetRoom
 * @param {Object} params.targetBed
 * @param {Date} [params.effectiveTransferDate]
 * @param {string|mongoose.Types.ObjectId} params.actorId
 * @returns {Promise<{ success: boolean, replacementContractId?: string, error?: string }>}
 */
export async function autoGenerateTransferContract({
  reservationId,
  activeStay,
  targetRoom,
  targetBed = {},
  effectiveTransferDate = new Date(),
  actorId,
}) {
  try {
    const oldContract = await Contract.findOne({
      reservationId,
      isCurrent: true,
    }).sort({ version: -1, createdAt: -1 });

    let replacementContract;
    if (oldContract) {
      logger.info(
        { oldContractId: oldContract._id, oldContractNumber: oldContract.contractNumber },
        "[AutoContract] Creating replacement contract for room transfer",
      );
      replacementContract = await createReplacementContractForTransfer({
        reservationId,
        stayId: activeStay?._id || oldContract.stayId,
        oldContract,
        targetRoom,
        targetBed,
        effectiveTransferDate,
        actorId,
      });
    } else {
      logger.info({ reservationId }, "[AutoContract] No previous current contract found; creating fresh draft for target room");
      replacementContract = await createDraftContract({
        reservationId,
        stayId: activeStay?._id || null,
        actorId,
      });
    }

    if (replacementContract.status !== "ready_for_generation") {
      const validation = await validateContractForGeneration(replacementContract);
      if (validation.valid) {
        await transitionContract(replacementContract, "ready_for_generation", actorId, "Transfer replacement contract auto-validated");
        Object.assign(replacementContract, validation.generationData.pricing);
        replacementContract.templateType = validation.template.templateId;
        replacementContract.templateVersion = validation.template.templateVersion;
        replacementContract.legalContentVersion = validation.template.legalContentVersion;
        replacementContract.validatedGenerationData = validation.generationData;
        replacementContract.lastValidatedAt = new Date();
        replacementContract.updatedBy = actorId;
        await replacementContract.save();
      } else {
        logger.warn(
          { contractId: replacementContract._id, missing: validation.missingFields, errors: validation.errors },
          "[AutoContract] Transfer contract validation incomplete; draft created for administrator review",
        );
        return {
          success: true,
          replacementContractId: String(replacementContract._id),
          contractNumber: replacementContract.contractNumber,
          status: replacementContract.status,
          incomplete: true,
        };
      }
    }

    logger.info(
      { contractId: replacementContract._id, contractNumber: replacementContract.contractNumber },
      "[AutoContract] Generating prepared PDF for room transfer replacement contract",
    );
    const result = await generatePreparedContractPdf({
      contractId: replacementContract._id,
      actorId,
      regenerationReason: `Auto-generated replacement for Room Transfer to Room ${targetRoom.roomNumber || targetRoom.name}`,
    });

    try {
      const tenant = await User.findById(replacementContract.tenantId).select("firstName lastName").lean();
      const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}`.trim() : replacementContract.tenantLegalName || "Tenant";
      notifyBranchAdminsSafe(
        replacementContract.branch,
        "contract_prepared",
        "Room Transfer Contract Ready",
        `Replacement contract for ${tenantName} (Room ${replacementContract.roomNumber}) was auto-generated and is ready for signing.`,
        {
          entityType: "contract",
          entityId: String(replacementContract._id),
          reservationId: replacementContract.reservationId ? String(replacementContract.reservationId) : null,
          actionUrl: replacementContract.reservationId
            ? `/admin/tenants?reservationId=${encodeURIComponent(String(replacementContract.reservationId))}`
            : "/admin/tenants",
        },
      );
    } catch (notifErr) {
      logger.warn({ err: notifErr }, "[AutoContract] Post-transfer notification error (non-fatal)");
    }

    const transferTenantId = replacementContract?.tenantId;
    if (transferTenantId) {
      if (typeof emitToUser === "function") {
        emitToUser(transferTenantId, "contract:updated", {
          contractId: String(result.contract._id),
          contractNumber: result.contract.contractNumber,
          status: result.contract.status,
          reservationId: String(reservationId),
        });
      }
    }

    if (typeof emitToAdmins === "function") {
      emitToAdmins("contract:updated", {
        contractId: String(result.contract._id),
        contractNumber: result.contract.contractNumber,
        status: result.contract.status,
        branch: replacementContract.branch,
      });
    }

    return {
      success: true,
      replacementContractId: String(result.contract._id),
      contractNumber: result.contract.contractNumber,
    };
  } catch (error) {
    logger.error({ err: error, reservationId }, "[AutoContract] Failed to auto-generate Transfer contract");
    try {
      notifyBranchAdminsSafe(
        targetRoom?.branch || "",
        "contract_error",
        "Transfer Contract Auto-Generation Alert",
        `Room transfer contract auto-generation encountered an issue: ${error.message || "Unknown error"}. Review required in Contracts workspace.`,
        {
          entityType: "reservation",
          entityId: String(reservationId),
          reservationId: String(reservationId),
          actionUrl: `/admin/tenants?reservationId=${encodeURIComponent(String(reservationId))}`,
        },
      );
    } catch (alertErr) {
      // Non-fatal
    }
    return { success: false, error: error.message, code: error.code };
  }
}

/**
 * Automatically creates and generates a prepared PDF successor Contract when
 * a lease renewal is accepted (renewStayWorkflow / respondToRenewalOffer).
 * The successor is created FINAL-eligible-but-not-yet-effective (isCurrent:
 * false, status draft -> generated) — it never touches oldContract's status
 * or isCurrent; only contractRenewalActivationService.activateDueRenewalContracts
 * flips both contracts, at the successor's actual leaseStartDate.
 *
 * @param {Object} params
 * @param {string|mongoose.Types.ObjectId} params.reservationId
 * @param {Object} params.oldContract - the tenant's current Contract document
 * @param {Object} params.newStay - the Stay document renewStayWorkflow just created
 * @param {string|mongoose.Types.ObjectId} params.actorId
 * @returns {Promise<{ success: boolean, successorContractId?: string, error?: string }>}
 */
export async function autoGenerateRenewalContract({
  reservationId,
  oldContract,
  newStay,
  actorId,
}) {
  try {
    if (!oldContract) {
      logger.warn({ reservationId }, "[AutoContract] Renewal contract skipped: no current Contract found");
      return { success: false, error: "PREVIOUS_CONTRACT_REQUIRED" };
    }

    logger.info(
      { oldContractId: oldContract._id, oldContractNumber: oldContract.contractNumber },
      "[AutoContract] Creating successor contract for lease renewal",
    );
    const successorContract = await createSuccessorContractForRenewal({
      reservationId,
      oldContract,
      newStay,
      actorId,
    });

    if (successorContract.status !== "ready_for_generation") {
      const validation = await validateContractForGeneration(successorContract);
      if (validation.valid) {
        await transitionContract(successorContract, "ready_for_generation", actorId, "Renewal successor contract auto-validated");
        Object.assign(successorContract, validation.generationData.pricing);
        successorContract.templateType = validation.template.templateId;
        successorContract.templateVersion = validation.template.templateVersion;
        successorContract.legalContentVersion = validation.template.legalContentVersion;
        successorContract.validatedGenerationData = validation.generationData;
        successorContract.lastValidatedAt = new Date();
        successorContract.updatedBy = actorId;
        await successorContract.save();
      } else {
        logger.warn(
          { contractId: successorContract._id, missing: validation.missingFields, errors: validation.errors },
          "[AutoContract] Renewal contract validation incomplete; draft created for administrator review",
        );
        return {
          success: true,
          successorContractId: String(successorContract._id),
          contractNumber: successorContract.contractNumber,
          status: successorContract.status,
          incomplete: true,
        };
      }
    }

    logger.info(
      { contractId: successorContract._id, contractNumber: successorContract.contractNumber },
      "[AutoContract] Generating prepared PDF for renewal successor contract",
    );
    const result = await generatePreparedContractPdf({
      contractId: successorContract._id,
      actorId,
      regenerationReason: `Auto-generated renewal successor for Room ${successorContract.roomNumber}`,
    });

    try {
      const tenant = await User.findById(successorContract.tenantId).select("firstName lastName").lean();
      const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}`.trim() : successorContract.tenantLegalName || "Tenant";
      notifyBranchAdminsSafe(
        successorContract.branch,
        "contract_prepared",
        "Renewal Contract Ready",
        `Renewal contract for ${tenantName} (Room ${successorContract.roomNumber}) was auto-generated and is ready for signing.`,
        {
          entityType: "contract",
          entityId: String(successorContract._id),
          reservationId: successorContract.reservationId ? String(successorContract.reservationId) : null,
          actionUrl: successorContract.reservationId
            ? `/admin/tenants?reservationId=${encodeURIComponent(String(successorContract.reservationId))}`
            : "/admin/tenants",
        },
      );
    } catch (notifErr) {
      logger.warn({ err: notifErr }, "[AutoContract] Post-renewal notification error (non-fatal)");
    }

    return {
      success: true,
      successorContractId: String(result.contract._id),
      contractNumber: result.contract.contractNumber,
    };
  } catch (error) {
    logger.error({ err: error, reservationId }, "[AutoContract] Failed to auto-generate Renewal contract");
    try {
      notifyBranchAdminsSafe(
        oldContract?.branch || "",
        "contract_error",
        "Renewal Contract Auto-Generation Alert",
        `Renewal contract auto-generation encountered an issue: ${error.message || "Unknown error"}. Review required in Contracts workspace.`,
        {
          entityType: "reservation",
          entityId: String(reservationId),
          reservationId: String(reservationId),
          actionUrl: `/admin/tenants?reservationId=${encodeURIComponent(String(reservationId))}`,
        },
      );
    } catch (alertErr) {
      // Non-fatal
    }
    return { success: false, error: error.message, code: error.code };
  }
}

async function notifyBranchAdminsSafe(branch, type, title, message, options = {}) {
  try {
    const { notifyBranchAdmins } = await import("./notifications/notificationService.js");
    await notifyBranchAdmins(branch, type, title, message, options);
  } catch (e) {
    // Non-fatal notification failure
  }
}

/**
 * Periodically checks for:
 * 1. Contracts nearing expiry (within 30 days) to send advance tenant renewal reminders.
 * 2. Active contracts that have passed their leaseEndDate without notice to transition to 'rolling' month-to-month.
 */
export async function checkAndRollExpiredContracts() {
  const now = new Date();
  const rolled = [];
  const reminded = [];

  try {
    // 1. Roll expired active contracts to rolling month-to-month
    const expiredActiveContracts = await Contract.find({
      status: { $in: ["active", "expiring_soon"] },
      isCurrent: true,
      leaseEndDate: { $lt: now },
    });

    for (const contract of expiredActiveContracts) {
      try {
        await transitionContract(
          contract,
          "rolling",
          null,
          "automatic_month_to_month_rollover",
        );
        rolled.push(contract._id);
        logger.info(
          { contractId: contract._id, contractNumber: contract.contractNumber },
          "[AutoContract] Transitioned expired active contract to rolling month-to-month",
        );
      } catch (err) {
        logger.warn(
          { err, contractId: contract._id },
          "[AutoContract] Failed to transition contract to rolling month-to-month",
        );
      }
    }

    // 2. 30-day advance expiry reminders
    const thirtyDaysAhead = dayjs().add(30, "day").toDate();
    const expiringSoonContracts = await Contract.find({
      status: "active",
      isCurrent: true,
      leaseEndDate: { $lte: thirtyDaysAhead, $gt: now },
      advanceRenewalPromptSentAt: null,
    });

    for (const contract of expiringSoonContracts) {
      try {
        contract.advanceRenewalPromptSentAt = new Date();
        await contract.save();

        if (contract.tenantId) {
          notify(
            contract.tenantId,
            "contract_expiring_soon",
            "Upcoming Lease Expiration",
            `Your lease contract is scheduled to end on ${dayjs(contract.leaseEndDate).format("MMMM D, YYYY")}. Please inform the front desk if you plan to renew or extend your stay.`,
            { entityType: "contract", entityId: String(contract._id), actionUrl: "/tenant/contracts" },
          ).catch(() => {});
        }
        reminded.push(contract._id);
      } catch (remindErr) {
        logger.warn(
          { err: remindErr, contractId: contract._id },
          "[AutoContract] Failed to dispatch 30-day renewal prompt",
        );
      }
    }
  } catch (error) {
    logger.error({ err: error }, "[AutoContract] checkAndRollExpiredContracts error");
  }

  return { rolledCount: rolled.length, remindedCount: reminded.length, rolled, reminded };
}
