import { beforeEach, describe, expect, jest, test } from "@jest/globals";
import dayjs from "dayjs";

const reservationFind = jest.fn();
const reservationFindById = jest.fn();
const reservationFindOverdueMoveIns = jest.fn();
const reservationUpdateOne = jest.fn();
const contractFind = jest.fn();
const autoGenerateMoveInContract = jest.fn();
const autoGenerateDepositSettledContract = jest.fn();
const roomFind = jest.fn();
const billUpdateMany = jest.fn();
const billFind = jest.fn();
const syncReservationUserLifecycle = jest.fn();
const updateOccupancyOnReservationChange = jest.fn();
const resolveBillStatus = jest.fn((bill) => bill.status);
const syncBillAmounts = jest.fn();
const getLifecyclePolicySettings = jest.fn(async () => ({
  noShowGraceDays: 7,
  stalePendingHours: 2,
  staleVisitPendingHours: 336,
  visitPendingWarnDays: 12,
  staleVisitApprovedHours: 48,
  stalePaymentPendingHours: 48,
  archiveCancelledAfterDays: 7,
}));
const getPenaltyRatePerDay = jest.fn(async () => 50);
const resolvePenaltyRatePerDay = jest.fn((rate) => rate || 50);
const dispatchDueScheduledAnnouncements = jest.fn();
const maintenanceRequestFind = jest.fn();
const notify = {
  general: jest.fn(),
  reservationExpired: jest.fn(),
  reservationNoShow: jest.fn(),
  penaltyApplied: jest.fn(),
  billDueReminder: jest.fn(),
  billingNotice: jest.fn(),
  overdueMoveIn: jest.fn(),
};

const makePopulateChain = (result) => {
  const chain = {
    populate: jest.fn(() => chain),
    sort: jest.fn(() => chain),
    lean: jest.fn(() => chain),
    select: jest.fn(() => chain),
    then: (resolve, reject) => Promise.resolve(result).then(resolve, reject),
    catch: (reject) => Promise.resolve(result).catch(reject),
    finally: (handler) => Promise.resolve(result).finally(handler),
  };
  return chain;
};

await jest.unstable_mockModule("../models/index.js", () => ({
  Reservation: {
    find: reservationFind,
    findById: reservationFindById,
    findOverdueMoveIns: reservationFindOverdueMoveIns,
    updateOne: reservationUpdateOne,
  },
  Room: {
    find: roomFind,
  },
  Bill: {
    updateMany: billUpdateMany,
    find: billFind,
  },
  User: {},
  MaintenanceRequest: {
    find: maintenanceRequestFind,
  },
  ChatConversation: {
    find: jest.fn(() => ({
      sort: jest.fn(() => ({
        lean: jest.fn(() => Promise.resolve([])),
      })),
      lean: jest.fn(() => Promise.resolve([])),
    })),
    updateMany: jest.fn(() => Promise.resolve({ modifiedCount: 0 })),
  },
  ChatMessage: {
    find: jest.fn(() => Promise.resolve([])),
    create: jest.fn(() => Promise.resolve({})),
  },
  Contract: {
    find: contractFind,
  },
}));

await jest.unstable_mockModule("../services/autoContractOrchestratorService.js", () => ({
  autoGenerateMoveInContract,
  autoGenerateDepositSettledContract,
}));

await jest.unstable_mockModule("../utils/reservationHelpers.js", () => ({
  syncReservationUserLifecycle,
}));

await jest.unstable_mockModule("./notificationService.js", () => ({
  default: notify,
  notify,
}));

await jest.unstable_mockModule("./occupancyManager.js", () => ({
  updateOccupancyOnReservationChange,
  releaseOrphanedBeds: jest.fn(),
}));

await jest.unstable_mockModule("../middleware/logger.js", () => ({
  default: {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

await jest.unstable_mockModule("../config/firebase.js", () => ({
  getAuth: jest.fn(() => null),
}));

await jest.unstable_mockModule("./billingPolicy.js", () => ({
  resolveBillStatus,
  syncBillAmounts,
}));

await jest.unstable_mockModule("./businessSettings.js", () => ({
  getLifecyclePolicySettings,
  getPenaltyRatePerDay,
  getLatePaymentGraceDays: jest.fn(async () => 1),
  resolvePenaltyRatePerDay,
  resolveLatePaymentGraceDays: (s, c) => (s !== undefined && s !== null ? Number(s) : (c !== undefined && c !== null ? Number(c) : 1)),
}));

await jest.unstable_mockModule("./rentGenerator.js", () => ({
  generateAutomatedRentBills: jest.fn(),
}));

await jest.unstable_mockModule("../services/contractRenewalActivationService.js", () => ({
  activateDueRenewalContracts: jest.fn(),
}));

await jest.unstable_mockModule("./announcementDispatch.js", () => ({
  dispatchDueScheduledAnnouncements,
}));

await jest.unstable_mockModule("./lifecycleNaming.js", () => ({
  CURRENT_RESIDENT_STATUS_QUERY: ["moveIn"],
  ACTIVE_OCCUPANCY_STATUS_QUERY: ["reserved", "moveIn"],
  readMoveInDate: (reservation) => reservation.moveInDate || null,
}));

const scheduler = await import("./scheduler.js");

const createReservation = (overrides = {}) => ({
  _id: "reservation-1",
  userId: { _id: "user-1" },
  roomId: { _id: "room-1", name: "Room 1" },
  status: "pending",
  notes: "",
  selectedBed: { id: "bed-1" },
  targetMoveInDate: new Date("2026-04-01T00:00:00.000Z"),
  moveInExtendedTo: null,
  save: jest.fn(async function save() {
    return this;
  }),
  populate: jest.fn(async function populate() {
    return this;
  }),
  ...overrides,
});

describe("scheduler jobs", () => {
  beforeEach(() => {
    reservationFind.mockReset();
    reservationFindById.mockReset();
    reservationFindOverdueMoveIns.mockReset();
    reservationUpdateOne.mockReset();
    reservationUpdateOne.mockResolvedValue({ modifiedCount: 1 });
    contractFind.mockReset();
    autoGenerateMoveInContract.mockReset();
    autoGenerateDepositSettledContract.mockReset();
    roomFind.mockReset();
    billUpdateMany.mockReset();
    billFind.mockReset();
    syncReservationUserLifecycle.mockReset();
    updateOccupancyOnReservationChange.mockReset();
    resolveBillStatus.mockReset();
    resolveBillStatus.mockImplementation((bill) => bill.status);
    syncBillAmounts.mockReset();
    getLifecyclePolicySettings.mockReset();
    getLifecyclePolicySettings.mockResolvedValue({
      noShowGraceDays: 7,
      stalePendingHours: 2,
      staleVisitPendingHours: 336,
      visitPendingWarnDays: 12,
      staleVisitApprovedHours: 48,
      stalePaymentPendingHours: 48,
      archiveCancelledAfterDays: 7,
    });
    getPenaltyRatePerDay.mockReset();
    getPenaltyRatePerDay.mockResolvedValue(50);
    resolvePenaltyRatePerDay.mockReset();
    resolvePenaltyRatePerDay.mockImplementation((rate) => rate || 50);
    dispatchDueScheduledAnnouncements.mockReset();
    notify.general.mockReset();
    notify.reservationExpired.mockReset();
    notify.reservationNoShow.mockReset();
    notify.penaltyApplied.mockReset();
    notify.billDueReminder.mockReset();
    notify.billingNotice.mockReset();
  });

  test("detectOverdueMoveIns flags reserved reservations past their move-in deadline as move_in_overdue", async () => {
    const overdue = createReservation({
      _id: "res-overdue-1",
      status: "reserved",
      targetMoveInDate: new Date("2020-01-01T00:00:00.000Z"),
      moveInExtendedTo: null,
    });
    reservationFindOverdueMoveIns.mockReturnValue(makePopulateChain([overdue]));

    await scheduler.detectOverdueMoveIns();

    expect(reservationUpdateOne).toHaveBeenCalledTimes(1);
    expect(reservationUpdateOne).toHaveBeenCalledWith(
      { _id: "res-overdue-1", status: "reserved" },
      { $set: { status: "move_in_overdue" } },
    );
    expect(notify.overdueMoveIn).toHaveBeenCalledTimes(1);
  });

  test("detectOverdueMoveIns sends a notification but never flags a reservation not still at reserved (system never auto-transitions out of overdue)", async () => {
    const alreadyFlagged = createReservation({
      _id: "res-overdue-2",
      status: "move_in_overdue",
      targetMoveInDate: new Date("2020-01-01T00:00:00.000Z"),
      moveInExtendedTo: null,
    });
    reservationFindOverdueMoveIns.mockReturnValue(makePopulateChain([alreadyFlagged]));

    await scheduler.detectOverdueMoveIns();

    expect(reservationUpdateOne).not.toHaveBeenCalled();
  });

  test("expireStaleReservations cancels stale reservations and syncs lifecycle", async () => {
    const reservation = createReservation({
      status: "pending",
      userId: { _id: "user-2" },
      roomId: { _id: "room-2", name: "Room 2" },
      createdAt: new Date("2026-04-01T00:00:00.000Z"),
      save: jest.fn(async function save() {
        return this;
      }),
      populate: jest.fn(async function populate() {
        return this;
      }),
    });

    reservationFind
      .mockReturnValueOnce(makePopulateChain([reservation]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]));
    roomFind.mockResolvedValue([]);

    await scheduler.expireStaleReservations();

    expect(getLifecyclePolicySettings).toHaveBeenCalledTimes(1);
    expect(reservation.status).toBe("cancelled");
    expect(reservation.save).toHaveBeenCalledTimes(1);
    expect(updateOccupancyOnReservationChange).toHaveBeenCalledTimes(1);
    expect(syncReservationUserLifecycle).toHaveBeenCalledWith(
      expect.objectContaining({
        status: "cancelled",
        previousStatus: "pending",
        userId: "user-2",
        roomId: "room-2",
        reservationId: "reservation-1",
        force: true,
      }),
    );
    expect(notify.reservationExpired).toHaveBeenCalledTimes(1);
  });

  test("expireStaleReservations uses configured lifecycle thresholds from business settings", async () => {
    reservationFind
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]));
    getLifecyclePolicySettings.mockResolvedValue({
      noShowGraceDays: 7,
      stalePendingHours: 9,
      staleVisitPendingHours: 240,
      visitPendingWarnDays: 12,
      staleVisitApprovedHours: 72,
      stalePaymentPendingHours: 60,
      archiveCancelledAfterDays: 14,
    });

    await scheduler.expireStaleReservations();

    const pendingCutoff = reservationFind.mock.calls[0][0].updatedAt.$lt;
    const visitPendingCutoff = reservationFind.mock.calls[1][0].createdAt.$lt;
    const approvedCutoff = reservationFind.mock.calls[2][0].visitDate.$lt;
    const paymentCutoff = reservationFind.mock.calls[3][0].updatedAt.$lt;

    const diffHours = (date) => (Date.now() - date.getTime()) / (1000 * 60 * 60);

    expect(diffHours(pendingCutoff)).toBeGreaterThan(8.5);
    expect(diffHours(pendingCutoff)).toBeLessThan(9.5);
    expect(diffHours(visitPendingCutoff)).toBeGreaterThan(239.5);
    expect(diffHours(visitPendingCutoff)).toBeLessThan(240.5);
    expect(diffHours(approvedCutoff)).toBeGreaterThan(71.5);
    expect(diffHours(approvedCutoff)).toBeLessThan(72.5);
    expect(diffHours(paymentCutoff)).toBeGreaterThan(59.5);
    expect(diffHours(paymentCutoff)).toBeLessThan(60.5);
  });

  test("expireStaleReservations checks updatedAt for pending reservations using 30-minute inactivity window", async () => {
    reservationFind
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]))
      .mockReturnValueOnce(makePopulateChain([]));
    getLifecyclePolicySettings.mockResolvedValue({
      noShowGraceDays: 7,
      stalePendingHours: 0.5,
      staleVisitPendingHours: 240,
      visitPendingWarnDays: 12,
      staleVisitApprovedHours: 72,
      stalePaymentPendingHours: 60,
      archiveCancelledAfterDays: 14,
    });

    await scheduler.expireStaleReservations();

    const pendingQuery = reservationFind.mock.calls[0][0];
    // Must filter on updatedAt for rolling inactivity
    expect(pendingQuery.updatedAt).toBeDefined();
    const diffMinutes = (Date.now() - pendingQuery.updatedAt.$lt.getTime()) / (1000 * 60);
    expect(diffMinutes).toBeGreaterThan(29);
    expect(diffMinutes).toBeLessThan(31);
  });

  test("cancelNoShowReservations cancels overdue reserved reservations and syncs lifecycle", async () => {
    const reservation = createReservation({
      status: "reserved",
      userId: { _id: "user-3" },
      roomId: { _id: "room-3", name: "Room 3" },
      targetMoveInDate: new Date("2026-03-01T00:00:00.000Z"),
      moveInExtendedTo: null,
      save: jest.fn(async function save() {
        return this;
      }),
      populate: jest.fn(async function populate() {
        return this;
      }),
    });

    reservationFind.mockReturnValue(makePopulateChain([reservation]));
    roomFind.mockResolvedValue([]);

    await scheduler.cancelNoShowReservations();

    expect(getLifecyclePolicySettings).toHaveBeenCalledTimes(1);
    expect(reservation.status).toBe("cancelled");
    expect(reservation.save).toHaveBeenCalledTimes(1);
    expect(updateOccupancyOnReservationChange).toHaveBeenCalledTimes(1);
    expect(syncReservationUserLifecycle).toHaveBeenCalledWith(
      expect.objectContaining({
        status: "cancelled",
        previousStatus: "reserved",
        userId: "user-3",
        roomId: "room-3",
        reservationId: "reservation-1",
        force: true,
      }),
    );
    expect(notify.reservationNoShow).toHaveBeenCalledTimes(1);
  });

  test("cancelNoShowReservations respects the configured no-show grace days", async () => {
    const reservation = createReservation({
      status: "reserved",
      userId: { _id: "user-4" },
      roomId: { _id: "room-4", name: "Room 4" },
      targetMoveInDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      save: jest.fn(async function save() {
        return this;
      }),
      populate: jest.fn(async function populate() {
        return this;
      }),
    });

    reservationFind.mockReturnValue(makePopulateChain([reservation]));
    getLifecyclePolicySettings.mockResolvedValue({
      noShowGraceDays: 10,
      stalePendingHours: 2,
      staleVisitPendingHours: 336,
      visitPendingWarnDays: 12,
      staleVisitApprovedHours: 48,
      stalePaymentPendingHours: 48,
      archiveCancelledAfterDays: 7,
    });

    await scheduler.cancelNoShowReservations();

    expect(reservation.status).toBe("reserved");
    expect(reservation.save).not.toHaveBeenCalled();
    expect(notify.reservationNoShow).not.toHaveBeenCalled();
  });

  test("markOverdueBills only marks records with due dates in the past", async () => {
    const overdueBill = {
      _id: "bill-1",
      userId: "user-1",
      billingMonth: new Date("2026-04-01T00:00:00.000Z"),
    };
    billFind.mockReturnValue(makePopulateChain([overdueBill]));
    billUpdateMany.mockResolvedValue({ modifiedCount: 1 });

    await scheduler.markOverdueBills();

    expect(billFind).toHaveBeenCalledWith(
      expect.objectContaining({
        status: { $in: ["pending", "partially-paid"] },
        dueDate: expect.objectContaining({ $ne: null, $lt: expect.any(Date) }),
        isArchived: false,
      }),
      { _id: 1, userId: 1, billingMonth: 1 },
    );
    expect(billUpdateMany).toHaveBeenCalledWith(
      expect.objectContaining({
        _id: { $in: ["bill-1"] },
      }),
      { $set: { status: "overdue" } },
    );
    expect(notify.billingNotice).toHaveBeenCalledWith(
      "user-1",
      expect.objectContaining({
        notificationType: "bill_due_reminder",
        billId: "bill-1",
        eventId: "status:overdue",
      }),
    );
  });

  test("computeOverduePenalties skips overdue bills that do not have due dates", async () => {
    const noDueDateBill = {
      _id: "bill-1",
      status: "overdue",
      dueDate: null,
      charges: { penalty: 0 },
      penaltyDetails: { ratePerDay: 50, daysLate: 0, appliedAt: null },
      userId: { _id: "user-1" },
      save: jest.fn(async function save() {
        return this;
      }),
    };

    billFind.mockReturnValue(makePopulateChain([noDueDateBill]));

    await scheduler.computeOverduePenalties();

    expect(noDueDateBill.save).not.toHaveBeenCalled();
    expect(syncBillAmounts).not.toHaveBeenCalled();
    expect(notify.penaltyApplied).not.toHaveBeenCalled();
  });

  test("computeOverduePenalties persists the first penalty before emitting its stable bill event", async () => {
    const overdueBill = {
      _id: "bill-penalty-1",
      status: "overdue",
      dueDate: dayjs().subtract(2, "day").toDate(),
      billingMonth: new Date("2026-08-01T00:00:00.000Z"),
      charges: { rent: 5000, penalty: 0 },
      penaltyDetails: { ratePerDay: 50, daysLate: 0, appliedAt: null },
      userId: { _id: "user-1" },
      save: jest.fn(async function save() {
        return this;
      }),
    };
    billFind.mockReturnValue(makePopulateChain([overdueBill]));

    await scheduler.computeOverduePenalties();

    expect(overdueBill.save).toHaveBeenCalledTimes(1);
    expect(notify.penaltyApplied).toHaveBeenCalledWith(
      "user-1",
      "August 2026",
      expect.any(Number),
      expect.any(Number),
      {
        billId: "bill-penalty-1",
        eventId: overdueBill.penaltyDetails.appliedAt,
      },
    );
    expect(overdueBill.save.mock.invocationCallOrder[0]).toBeLessThan(
      notify.penaltyApplied.mock.invocationCallOrder[0],
    );
  });

  test("dispatchScheduledAnnouncements runs the scheduled announcement dispatcher", async () => {
    dispatchDueScheduledAnnouncements.mockResolvedValue({
      dueCount: 2,
      dispatchedCount: 1,
    });

    await scheduler.dispatchScheduledAnnouncements();

    expect(dispatchDueScheduledAnnouncements).toHaveBeenCalledTimes(1);
  });

  test("autoCompleteResolvedTickets transitions 7-day inactive resolved tickets to completed", async () => {
    const expiredTicket = {
      _id: "maint-701",
      ticketNumber: "MNT-2026-701",
      status: "resolved",
      resolved_at: dayjs().subtract(8, "day").toDate(),
      statusHistory: [],
      userId: "user-123",
      save: jest.fn(async function save() {
        return this;
      }),
    };

    maintenanceRequestFind.mockResolvedValue([expiredTicket]);

    await scheduler.autoCompleteResolvedTickets();

    expect(expiredTicket.status).toBe("completed");
    expect(expiredTicket.closed_at).toBeDefined();
    expect(expiredTicket.statusHistory).toHaveLength(1);
    expect(expiredTicket.statusHistory[0].event).toBe("auto_completed_after_7_days");
    expect(expiredTicket.save).toHaveBeenCalledTimes(1);
    expect(notify.general).toHaveBeenCalledWith(
      "user-123",
      "Maintenance Request Completed",
      expect.stringContaining("MNT-2026-701"),
      expect.any(Object)
    );
  });

  test("reconcileMissingContractGeneration retries the Move-In generator for a moved-in, formally-approved reservation whose Contract never generated", async () => {
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-1", reservationId: "res-1", status: "draft", createdBy: "admin-1", updatedBy: null, bedId: "bed-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "moveIn",
      userId: "tenant-1",
      roomId: "room-1",
      applicationReviewedAt: new Date("2026-08-10T00:00:00.000Z"),
      applicationReviewedBy: "admin-1",
      initialPaymentStatus: "paid",
      paymentStatus: "paid_in_full",
      confirmedMoveInDate: new Date("2026-08-11T16:00:00.000Z"),
      moveInDate: null,
    }));
    autoGenerateMoveInContract.mockResolvedValue({ success: true, contractId: "contract-1" });

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateMoveInContract).toHaveBeenCalledWith({
      reservationId: "res-1",
      actualMoveInDate: new Date("2026-08-11T16:00:00.000Z"),
      actorId: "admin-1",
    });
    expect(autoGenerateDepositSettledContract).not.toHaveBeenCalled();
  });

  test("reconcileMissingContractGeneration retries the deposit-settled generator when the reservation is paid, approved, but not yet moved in", async () => {
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-2", reservationId: "res-2", status: "ready_for_generation", createdBy: "admin-2", updatedBy: "admin-3", bedId: "bed-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "reserved",
      userId: "tenant-2",
      roomId: "room-2",
      applicationReviewedAt: new Date("2026-08-10T00:00:00.000Z"),
      applicationReviewedBy: "admin-3",
      initialPaymentStatus: "paid",
      paymentStatus: "paid_in_full",
    }));
    autoGenerateDepositSettledContract.mockResolvedValue({ success: true, contractId: "contract-2" });

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateDepositSettledContract).toHaveBeenCalledWith({
      reservationId: "res-2",
      actorId: "admin-3",
    });
    expect(autoGenerateMoveInContract).not.toHaveBeenCalled();
  });

  test("reconcileMissingContractGeneration skips a paid reservation that was never formally application-reviewed, instead of retrying it forever", async () => {
    // Mirrors a real production shape: paid in full, but applicationReviewedBy
    // was never recorded, so the real validator rejects it with
    // CONTRACT_SOURCE_APPROVAL_REQUIRED — Job 19 must not treat "paid" alone
    // as generatable.
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-4", reservationId: "res-4", status: "draft", createdBy: "admin-1", bedId: "bed-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "reserved",
      userId: "tenant-4",
      roomId: "room-4",
      applicationReviewedAt: new Date("2026-08-10T00:00:00.000Z"),
      applicationReviewedBy: null,
      paymentStatus: "paid_in_full",
    }));

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateMoveInContract).not.toHaveBeenCalled();
    expect(autoGenerateDepositSettledContract).not.toHaveBeenCalled();
  });

  test("reconcileMissingContractGeneration skips a moved-in reservation whose legacy approval evidence is incomplete", async () => {
    // moveIn + paid_in_full alone used to be treated as eligible by the old
    // heuristic, but paid_in_full is not in the legacy-compatibility
    // allowlist (["partial", "paid"]) and there is no applicationReviewedBy
    // — the real validator rejects this with RESERVATION_LEGACY_VERIFICATION_REQUIRED.
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-5", reservationId: "res-5", status: "draft", createdBy: "admin-1", bedId: "bed-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "moveIn",
      userId: "tenant-5",
      roomId: "room-5",
      applicationReviewedAt: null,
      applicationReviewedBy: null,
      paymentStatus: "paid_in_full",
      confirmedMoveInDate: new Date("2026-08-11T16:00:00.000Z"),
    }));

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateMoveInContract).not.toHaveBeenCalled();
    expect(autoGenerateDepositSettledContract).not.toHaveBeenCalled();
  });

  test("reconcileMissingContractGeneration skips an otherwise-ready reservation with an open cancellation request", async () => {
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-6", reservationId: "res-6", status: "ready_for_generation", createdBy: "admin-1", bedId: "bed-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "reserved",
      userId: "tenant-6",
      roomId: "room-6",
      applicationReviewedAt: new Date("2026-08-10T00:00:00.000Z"),
      applicationReviewedBy: "admin-1",
      paymentStatus: "paid_in_full",
      cancellationRequested: true,
      cancellationStatus: "pending",
    }));

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateMoveInContract).not.toHaveBeenCalled();
    expect(autoGenerateDepositSettledContract).not.toHaveBeenCalled();
  });

  test("reconcileMissingContractGeneration leaves a stuck Contract alone when neither trigger condition has happened yet", async () => {
    contractFind.mockReturnValue(makePopulateChain([
      { _id: "contract-3", reservationId: "res-3", status: "draft", createdBy: "admin-1" },
    ]));
    reservationFindById.mockReturnValue(makePopulateChain({
      status: "reserved",
      initialPaymentStatus: "not_created",
      paymentStatus: "pending",
    }));

    await scheduler.reconcileMissingContractGeneration();

    expect(autoGenerateMoveInContract).not.toHaveBeenCalled();
    expect(autoGenerateDepositSettledContract).not.toHaveBeenCalled();
  });
});
